# db_automation/__init__.py
# Intentionally left empty to prevent circular imports.
# Import directly from submodules instead:
#   from db_automation.models import User, ...
#   from db_automation.services import UserService, ...
#   from db_automation.database import get_db, Base, ...
# from app.models.counters import Counter 
# from app.models.appointment_slots import AppointmentSlot