// Core Services - Barrel Export
export { AuthService } from './auth.service';
export { DoctorService } from './doctor.service';
export { HospitalService } from './hospital.service';
export { QueueService } from './queue.service';
export { TokenService } from './token.service';
export { DashboardService } from './dashboard.service';
export { PaymentService } from './payment.service';
export { ConsultationService } from './consultation.service';
export { PharmacyService } from './pharmacy.service';
export { NotificationService } from './notification.service';
export { UserProfileService } from './user-profile.service';
export { StaffPortalService } from './staff-portal.service';
export { ReceptionService } from './reception.service';
export { PatientActionsService } from './patient-actions.service';
export { AiService } from './ai.service';
export { ExternalPosService } from './external-pos.service';
export { SystemService } from './system.service';
